name: 'Run Java program'
description: 'Checks out repository, install java and run java program'
runs:
  using: 'composite'
  steps:
    - name: setup java for caller environment
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '25'
