name: 'Run Java program'
description: 'Checks out repository, install java and run java program'
inputs:
  javaclass:
    description: java file name to run
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: setup java for caller environment
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '25'
    - name: Run java class
      shell: bash
      run: java ${{inputs.javaclass}}
