name: Reusable calculator workflow
on:
  workflow_call:
    inputs:
      operand1:
        description: This is first operand
        required: true
        default: 1
        type: number
      operand2:
        description: This is second operand
        required: true
        default: 1
        type: number
    # Map the workflow outputs to job outputs
    outputs:
      result:
        description: "The first output string"
        value: ${{ jobs.calculator_job.outputs.output1 }}
      multiplication:
        description: "The second output string"
        value: ${{ jobs.calculator_job.outputs.output2 }}

jobs:
  calculator_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.calc_step.outputs.result }}
      output2: ${{ steps.multiplication.outputs.result }}
    steps:
      - id: calc_step
        run: |
          SUM=$(( ${{inputs.operand1}} + ${{inputs.operand2}} )) 
          echo "result=$SUM" >> $GITHUB_OUTPUT
      - id: multiplication
        run: |
          SUM=$(( ${{inputs.operand1}} * ${{inputs.operand2}} )) 
          echo "result=$SUM" >> $GITHUB_OUTPUT
