name: Controlling Workflow

on: push
jobs:
  first-job:
    runs-on: ubuntu-slim
    steps:
      - name: Print greeting
        run: echo "Jay Mataji!!"
      - name: Print bye greeting
        run: echo "Blale, Jay Mataji!!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '25'
        id: run-java
      - run: java C.java
      - name: After C Java completes
        if: failure() && steps.run-java.outcome == 'failure'
        run: echo "After C Java completes"
      - name: test
        run: echo "test..!!"
  third-job:
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '25'
      - run: java C.java
  fourth-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '25'
      - run: java C.java
