name: Reusable Calculator
on:
  workflow_call:
    inputs:
      num1:
        required: true
        type: number
      num2:
        required: true
        type: number
    outputs:
      result:
        description: "The sum of two numbers"
        value: ${{ jobs.calculate.outputs.sum }}

jobs:
  calculate:
    runs-on: ubuntu-latest
    outputs:
      sum: ${{ steps.calc_step.outputs.total }}
    steps:
      - id: calc_step
        run: |
          TOTAL=$(( ${{ inputs.num1 }} + ${{ inputs.num2 }} ))
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
