name: Uses composite action
on: workflow_dispatch
env:
  MY_VAR: Agharu che aato ..!
jobs:
  composite-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Use custom composite action
        uses: ./.github/actions/composite-runjava
      - name: run java program
        run: java T.java
