name: Uses composite action
on: workflow_dispatch
env:
  MY_VAR: Agharu che aato ..!
jobs:
  composite-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo #GitHub-hosted runners do not automatically contain your code. Without actions/checkout, the runner cannot find your action.yml or Dockerfile
        uses: actions/checkout@v6
      - name: Use custom composite action
        uses: ./.github/actions/composite-runjava
        with:
          javaclass: C.java
